### ISSUE TITLE
Ways to open new tabs

### ISSUE THREAD

**Issue by anewuser** [igorlogius/open-in-temp-container#1]
Hello. What do you think of adding these options to your extension? They'd make it possible for me to replace Temporary Containers with it:

* [x] Add an option to set the button action to `Open a new tab in a new temporary container` instead of duplicating the current tab
* [x] Add a shortcut to open a new tab in a new temporary container
* [x] Add a shortcut to open a new tab in the same container as the current tab

**Comment by igorlogius** [comment]
1) and 2) should be rather easy to add. 3) would require a bit more work but seems doable. 
I'll see what i can do.

**Comment by igorlogius** [comment]
The issue should be fixed with `1.1.5`.

@anewuser The issue is now assigned to you to double check.

You can close the ticket if the issue is resolved for you. If it is not, please let me know and i'll take another look into it.

**Comment by anewuser** [comment]
The extension button and the `Open newtab in temp container` shortcut are opening blank tabs instead of showing my Firefox Home shortcuts. Apparently you don't need to pass any URI parameter to open new tabs:

>The New Tab page (`about:newtab`) can be opened if no value for URL is provided.
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

**Comment by igorlogius** [comment]
The issue should be fixed with `1.1.9`

@anewuser The issue is now assigned to you to double check.

You can close the ticket if the issue is resolved for you. If it is not, please let me know and i'll take another look into it.

**Comment by anewuser** [comment]
Firefox Home is always displayed now. Thank you.
