### ISSUE TITLE
Feature request: always open a site in temp container 

### ISSUE THREAD

**Issue by ivysrono** [igorlogius/open-in-temp-container#11]
[mozilla/multi-account-containers](https://github.com/mozilla/multi-account-containers#readme) support [always-open-a-site-in-a-container](https://support.mozilla.org/en-US/kb/containers#w_always-open-a-site-in-a-container) , while I'd like to always open a site in temp container.

**Comment by igorlogius** [comment]
Redirects are kind of annoying for this kind of usage and now i remember why i initally made this addon as a manual enhanced action  ... *sigh* ... i'll have to think about this a bit, before making any decisions.

**Comment by igorlogius** [comment]
https://github.com/igorlogius/open-in-temp-container/assets/67047467/12554f45-96dc-4242-af36-a5a0bf4f8e06

Auto Mode: OFF (aka. Manual mode): 
`If a tab which is not already in any container navigates to a URL which matches any of the listed RegExs will be reopened into a Temp Container.`

Auto Mode: ON 
`If a tab which is not already in any container navigates to a URL that is not listed it will be reopened into a Temp Container`

NOTES: 
- Addional features like locking a temp container to a specific domain or similar more special usecases are out of scope.

**Comment by igorlogius** [comment]
> I have one bookmark `A`.
> 
> Click and open A in Temp1;
> 
> Click and open A in new tab —— this new tab is Temp1 or Temp2?

Answer: `Temp 2`

**Comment by igorlogius** [comment]
part of `1.1.18`

**Comment by anewuser** [comment]
To automatically open articles from all Wikipedia versions except for the English version in temporary containers, you can use this rule: `^https:\/\/(?!en)\w+\.wikipedia`
