### ISSUE TITLE
[Feat] Add interoperability for MAC/FC / [Bug] tabs open twice with MAC/FC

### ISSUE THREAD

**Issue by ivysrono** [igorlogius/open-in-temp-container#13]
## Short Description:

Having OiTC together with [Contain Facebook](https://github.com/mozilla/contain-facebook) or [MAC](https://github.com/mozilla/multi-account-containers) installed opens managed tabs twice.

## Affected Version(s):

- 1.1.20 with auto mode enabled.

## Steps to Reproduce:

1. install OiTC.
2. install MAC/CF.
3. 
- If install CF, visit https://www.facebook.com/ ;

- If install MAC, set a url, for example: https://example.com/ to always open in specific container (for example personal container), then visit the url.

## Expected Result:

One tab should open in the facebook/personal container.

## Actual Result:

Two tabs open in both in the facebook/personal container.

## Additional Information (Screenshots/captures/...):

- Issue did not accure with version 1.1.19 and before.

- Issue did not accure with [Google Container](https://github.com/containers-everywhere/contain-google).

**Comment by igorlogius** [comment]
> https://github.com/mozilla/contain-facebook
> https://github.com/mozilla/multi-account-containers

multiple container addons, especially those who do automatic stuff tend to interfer with each other. 

I suspect the fix for the #12 which adds an earlier hook into the webNavigation, now hits before the container-facebook or multi-acount-containers hooks are able to intercept. This is a bit sad but to be frank, even that it worked before it was never intended or supported feature  and just worked per chance. 

And i dont really intend to support cross compatabilies with other addons, even if those are widely used. If there are many people having an issue with this i might consider investing some time ... to look for a workaround, but ... it's just too much work for a single developer. 

I'll keep this issue open with the `Help Wanted` label, in case somebody else wants to look into it and suggest a fix or make a pull request.

**Comment by igorlogius** [comment]
I am also not quite sure if i understand your steps to reproduce. 
Could you try editing your post to follow this format: 


### Short Description:
Having OiTC together with [Contain Facebook](https://github.com/mozilla/contain-facebook) or [MAC](https://github.com/mozilla/multi-account-containers) installed opens managed tabs twice

### Affected Version(s):

- 1.1.20

### Steps to Reproduce: 

1. install OiTC
2. install MAC/CF 
3. Set a url, for example: `https://example.com/` to always open in specific container (for example personal container)
4. ... ??? ... 

### Expected Result: 
One tab should open in the personal container

### Actual Result:
Two tabs open in both in the personal container

### Additional Information (Screenshots/captures/...): 
- Issue did not accure with version `1.1.19` and before.

**Comment by igorlogius** [comment]
The Mozilla container addons seems to have specific permissons (managment API) and code to be detect if each other 

``` 
async function isMACAddonEnabled() {
    try {
        const macAddonInfo = await browser.management.get(MAC_ADDON_ID);
        if (macAddonInfo.enabled) {
            sendJailedDomainsToMAC();
            return true;
        }
    } catch (e) {
        return false;
    }
    return false;
}
```

This infomration is later used to 

```
async function getMACAssignment(url) {
    if (!macAddonEnabled) {
        return false;
    }
    try {
        const assignment = await browser.runtime.sendMessage(MAC_ADDON_ID, {
            method: "getAssignment",
            url
        });
        return assignment;
    } catch (e) {
        return false;
    }
}
```

It is possible to emulate this ... but it would require addional permissions (managment API) and it would only work with addons specifically designed to work like this, all other container addons would still not work.

**Comment by igorlogius** [comment]
Sidenote: Google Container is not a offical addon by mozilla, so it working is just luck.

**Comment by igorlogius** [comment]
@ivysrono you might want to add which options you enabled in OiTC in your steps to reproduce. (Auto Mode y/n)

**Comment by igorlogius** [comment]
no auto mode, no problem :-)
