### ISSUE TITLE
Allow specifying source URLs

### ISSUE THREAD

**Issue by Gitoffthelawn** [igorlogius/open-in-temp-container#15]
**Is your feature request related to a problem? Please describe.**
The extension's UI currently allows the user to only specify regex ***destination*** URLs for temporary containers.  I would like to specify regex ***source*** URLs.

**Describe the solution you'd like**
Please allow the user to specify regex ***source*** and/or ***destination*** URLs for which to open temporary containers.

For example, let's say site `example.com` has a bunch of links.  Let's also say you want each of those links to open in its open unique temporary container (a unique temporary container for each link).  In this example, `example.com` is the ***source*** URL.

**Describe alternatives you've considered**
Using the Temporary Containers extension.

**Additional context**
Thank you!

**Comment by igorlogius** [comment]
https://github.com/igorlogius/open-in-temp-container/assets/67047467/777bec43-11cf-4a4e-9a5b-501a13629570
