### ISSUE TITLE
Simplifying the options

### ISSUE THREAD

**Issue by anewuser** [igorlogius/open-in-temp-container#16]
Hello. Why do you always hide old issues? This makes it harder for people to understand the progress of the project and what features have already been discussed. 

I have some suggestions to simplify the Options page:

![toolbar](https://github.com/igorlogius/open-in-temp-container/assets/6733770/62f692b8-6683-482a-9db1-590f68a87666)

![rules](https://github.com/igorlogius/open-in-temp-container/assets/6733770/4b65d29e-764a-49eb-9727-898d4b0ff207)

"Select colors to use for temp containers (does not effect existing temp  containers)" -> "Select colors to use for **new** temp containers"
"Hold CTRL to" -> "Hold CTRL down to"

**Comment by igorlogius** [comment]
![Screenshot_2024-03-30_23-41-52](https://github.com/igorlogius/open-in-temp-container/assets/67047467/58b57454-f3c8-4d12-9a03-0386abd5c8cf)

**Comment by anewuser** [comment]
@igorlogius The new `Toolbar button` option is resetting itself every I open the options.

**Comment by igorlogius** [comment]
@anewuser 

I'll look into it

**Comment by igorlogius** [comment]
seems like i forgot to change a typ check , should be fixed now

**Comment by anewuser** [comment]
Thank you!
