### ISSUE TITLE
Delayed deletion

### ISSUE THREAD

**Issue by anewuser** [igorlogius/open-in-temp-container#3]
Hello. URLs that you access in temporary containers created with this extension currently stay in your history, but they're removed from your list of recently closed tabs (and Firefox View) as soon as the container is deleted. Could you add an option to delay the deletion of containers for X minutes?

**Comment by igorlogius** [comment]
Should be doable ... the "cleanup time" is currently just a static value 5000ms ... but i dont see an issue with exposing that option on a preference page.

**Comment by igorlogius** [comment]
The issue should be fixed with 1.1.7

@anewuser The issue is now assigned to you to double check.

You can close the ticket if the issue is resolved for you. If it is not, please let me know and i'll take another look into it.

**Comment by anewuser** [comment]
It seems that the new setting is working fine. Thank you.
