### ISSUE TITLE
Containers not deleted after restarting Firefox or reloading the extension

### ISSUE THREAD

**Issue by anewuser** [igorlogius/open-in-temp-container#4]
**Describe the bug**
If you close Firefox before closing a temporary container, or turn the extension on and off , the container won't be deleted.

**To Reproduce**
1. Open a tab in a temporary container
2. Restart Firefox
3. Check `about:preferences#containers`

**Expected behavior**
The extension should check for and delete old temporary containers.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 119.0

**Comment by igorlogius** [comment]
Thanks for the report. I'll look into it and be back with an analysis later.

**Comment by igorlogius** [comment]
seems fixed with  `1.1.4`

**Comment by anewuser** [comment]
Leftover containers are being deleted now. Thank you.
