### ISSUE TITLE
Maybe mention use cases on the download page?

### ISSUE THREAD

**Issue by anewuser** [igorlogius/open-in-temp-container#6]
To make this extension more discoverable for potential users, especially those who don't even know about containers, maybe you could add some examples with keywords to its description on AMO, like:

* Access multiple Gmail, Outlook, and other email accounts without staying logged in
* Test sites with different logins
* If you're having issues with adblockers on Youtube, but videos still play fine in private windows, you can watch videos without ads in a temporary container instead
* Bypass paywalls on some sites that limit the number of articles you can read anonymously. Note: this only works for some sites

**Comment by igorlogius** [comment]
I could add some references that explain a bit more about containers, but i wouldn't want to advertise for "site specific features", like adblocking or paywalls.
