### ISSUE TITLE
Open current tab in N temporary containers

### ISSUE THREAD

**Issue by ivysrono** [igorlogius/open-in-temp-container#8]
[Container Opener](https://addons.mozilla.org/firefox/addon/container-opener/) only open current tab in all Already existing containers, however, I'd like to open current tab in 10 temporary containers.

**Comment by igorlogius** [comment]
Absolutely doable, but i don't have a clear picture how a good user workflow for this could look like. Suggestions?

**Comment by igorlogius** [comment]
Possiblities include:

- Shortcuts + for N duplication (with N configurable on the option page)
- Context Menu on the Tab (with sub entries for different duplication, configurable on the option page)
- Shortcut or content enty that opens a new tab where the user can select from a set of duplication options (configurable on the option page)

**Comment by igorlogius** [comment]
> Enough!

I take it, you'd be fine with either of the options. I'll see which one i can add in a timely manner.

**Comment by igorlogius** [comment]
![2024-02-28_18-06](https://github.com/igorlogius/open-in-temp-container/assets/67047467/9db6c3f1-7a14-48cd-b095-b601f7e37d2d)
![2024-02-28_18-10](https://github.com/igorlogius/open-in-temp-container/assets/67047467/b61fd59f-5079-4710-b88b-fa5e9e03fb56)
![2024-02-28_18-11](https://github.com/igorlogius/open-in-temp-container/assets/67047467/2a9b448e-e53a-45f6-91f9-298f6d4e40b7)

**Comment by igorlogius** [comment]
https://github.com/igorlogius/open-in-temp-container/assets/67047467/9ec9fab6-d509-4e0d-a5b3-2936dc230c6c

**Comment by igorlogius** [comment]
Done
