### ISSUE TITLE
Bug: open bookmark don't support folder / non-functional entry on bookmark folders

### ISSUE THREAD

**Issue by ivysrono** [igorlogius/open-in-temp-container#9]
**Describe the bug**
Menu show in both bookmark and bookmark folder, however, click it could't open folder's bookmarks, while open only one bookmark is OK.

**To Reproduce**
1. Enable Bookmark Permission
2. right click on a Bookmark Folder
3. The context menu opens and the "Open in Temp Container" entry is visible 
4. Click on the Entry 

**Expected Result**
Clicking the Context entry should open all the containing Bookmarks in seperate Temp containers

**Actual Result**
nothing happens

**Comment by igorlogius** [comment]
I guess there are technically 2 ways to "fix" this aka. handle the current inconsistentcy with 

1) remove the menu entry on the folders
2) add a function like opening the containing bookmarks all in temporary containers

**Comment by igorlogius** [comment]
https://github.com/igorlogius/open-in-temp-container/assets/67047467/47f368d4-6efe-417c-a810-005ea439b9eb

Fixed/Done
